# Change these first
owner: matbyte-com # Your GitHub organization or username, where this repository lives
repo: vyhub-status # The name of this repository

sites:
  - name: VyHub Homepage
    url: https://vyhub.net
  - name: VyHub API
  - name: VyHub Frontend

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vyhub.net
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/c44pLFe.png
  name: VyHub Status
  introTitle: "VyHub - The all-in-one management & monetization platformfor your gaming community"
  introMessage: On this page you can see the status of all VyHub services
    - title: Status
      href: /
    - title: Homepage
      href: https://vyhub.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
